"""add events pageviews funnels funnel_steps

Revision ID: 91a6cb22a81b
Revises: d4d28a0eaa3a
Create Date: 2026-04-19 05:13:29.566752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91a6cb22a81b'
down_revision: Union[str, None] = 'd4d28a0eaa3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id', 'occurred_at')
    )
    op.create_index('ix_events_tenant_time', 'events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_tenant_type', 'events', ['tenant_id', 'event_type'], unique=False)
    op.create_table('funnels',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_funnels_tenant', 'funnels', ['tenant_id'], unique=False)
    op.create_table('pageviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pageviews_tenant_time', 'pageviews', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_pageviews_tenant_url', 'pageviews', ['tenant_id', 'url'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('funnel_steps',
    sa.Column('funnel_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url_pattern', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_funnel_steps_funnel', 'funnel_steps', ['funnel_id', 'position'], unique=False)
    op.execute(
        "SELECT create_hypertable('events', 'occurred_at', "
        "chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_funnel_steps_funnel', table_name='funnel_steps')
    op.drop_table('funnel_steps')
    op.drop_table('users')
    op.drop_index('ix_pageviews_tenant_url', table_name='pageviews')
    op.drop_index('ix_pageviews_tenant_time', table_name='pageviews')
    op.drop_table('pageviews')
    op.drop_index('ix_funnels_tenant', table_name='funnels')
    op.drop_table('funnels')
    op.drop_index('ix_events_tenant_type', table_name='events')
    op.drop_index('ix_events_tenant_time', table_name='events')
    op.drop_table('events')
    op.drop_table('tenants')
    # ### end Alembic commands ###
